# Generated by Django 5.0.6 on 2026-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
