# Generated by Django 5.2.13 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assets', models.JSONField()),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('forex', 'Forex')], max_length=20)),
                ('frequency', models.CharField(choices=[('1d', 'Daily'), ('1h', 'Hourly'), ('5m', '5 Minutes')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_source', models.CharField(default='yfinance', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
