# Generated by Django 5.2.13 on 2026-04-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_metrics', models.JSONField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='experiments.experiment')),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.modelconfig')),
            ],
        ),
    ]
