# Generated by Django 5.0.6 on 2026-05-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='backtest_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='backtest_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
