version: "3.9"

services:
  backend:
    network_mode: bridge
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app

  frontend:
    network_mode: bridge
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    stdin_open: true
    tty: true
  